/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Saturn.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Saturn.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bake.geometry} material={materials['Material.001']} scale={1.006} />
      <mesh geometry={nodes.Ring001.geometry} material={materials['Material.003']} />
    </group>
  )
}

useGLTF.preload('/Saturn.glb')
